### ISSUE TITLE
Add feature to delete past expenses

### ISSUE THREAD

**Issue by anqichen9856** [AY1920S1-CS2103T-T11-1/main#10]
User story:
As a YEP (Youth Expedition Project) organizer who is in charge of logistics for my overseas project, I can delete a previous expense so that I do not keep track of expenses that have been reimbursed by Youth Corps Singapore.

**Comment by briyanii** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add feature to remove previously entered expenses](https://trello.com/c/fPOXwmG8/11-add-feature-to-remove-previously-entered-expenses)
