### ISSUE TITLE
GUI does not reflect budgets refreshing

### ISSUE THREAD

**Issue by czkay** [AY1920S1-CS2103T-T11-1/main#214]
GUI only shows the newly refreshed budget after a command has been inputted (i.e. GUI does not refresh by itself).

Can be reproduced by changing system time on computer.

Related to #174

**Comment by briyanii** [comment]
maybe we should remain as it, to avoid having to do constant checks for system time.
and just mention this in the UG.

**Comment by czkay** [comment]
@briyanii We already do constant checks for system time because of Events, so that shouldn't be a problem. Every time system time is updated, all budgets are checked and refreshed if needed. Maybe we can make the GUI check for such changes, but it's low-priority for now.
