### ISSUE TITLE
Budget attributes not working after undo-ing of adding expense

### ISSUE THREAD

**Issue by qweiping31415** [AY1920S1-CS2103T-T11-1/main#248]
Follow the steps to replicate the bug:
1. go to a non-default budget
2. add an expense
3. undo

The changes are reflected in the Expense List, but not  on the Budget panel  in the current session. The bug seems to be resolved when the user restarts the application, and the Budget attributes such as Budget's expense list as well as the progress bar are correctly reflected.

This affects the testability of other heavily coupled components such as Statistics.

**Comment by czkay** [comment]
![image](https://user-images.githubusercontent.com/54061046/68096554-6878e080-feec-11e9-99f9-de22802bf1a3.png)
Uncommenting the line above fixes the bug but re-introduces #211
