### ISSUE TITLE
Multiple UG/DG

### ISSUE THREAD

**Issue by damithc** [AY1920S1-CS2103T-T11-1/main#308]
Guys, you have multiple UG/DG versions. The latest version is too big in size and too pixelated to be of use/\. Do we take the previous version or are you able to give a new version that is more usable?

**Comment by czkay** [comment]
Prof @damithc, sorry about that. We will fix the size and resolution problems and submit a new usable UGDG before 2359 tonight.

**Comment by czkay** [comment]
Prof @damithc, we have submitted a usable UG and DG. Thank you!

**Comment by damithc** [comment]
Noted @czkay
