### ISSUE TITLE
Add feature to send reminders for events

### ISSUE THREAD

**Issue by anqichen9856** [AY1920S1-CS2103T-T11-1/main#33]
As a forgetful person, I want the app to be able to notify me of upcoming birthdays/anniversaries which may require me to budget for.

**Comment by briyanii** [comment]
may involve additional features like a calendar

**Comment by anqichen9856** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Send reminder for anniversaries](https://trello.com/c/uNpMrxlB/16-send-reminder-for-anniversaries)

**Comment by briyanii** [comment]
minimally implemented in #47
