### ISSUE TITLE
Add feature to easily enter NUS food stall expense from menu

### ISSUE THREAD

**Issue by briyanii** [AY1920S1-CS2103T-T11-1/main#34]
[NICE-TO-HAVE] 
[WILL BE TEDIOUS AF]
[SHORTCUT]
As an NUS student, and lazy person, I want to be able to add the cost of food I buy in school by saying e.g. “deck steamed chicken rice” and have it automatically add the expense without me having to enter the details and prices.

enhancement for #13

**Comment by anqichen9856** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feature: Add NUS food stall items](https://trello.com/c/FDqL7juZ/21-feature-add-nus-food-stall-items)
