### ISSUE TITLE
Add feature to undo expense

### ISSUE THREAD

**Issue by czkay** [AY1920S1-CS2103T-T11-1/main#6]
[UNDO REDO]
As a careless person who is prone to typos, I can undo my previous command, so that I do not enter the wrong amount for my expenses.

**Comment by briyanii** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feature: Undo last entered expense](https://trello.com/c/xnsPxJz5/18-feature-undo-last-entered-expense)
