### ISSUE TITLE
Update GUI to change color of budget status bar when close to budget

### ISSUE THREAD

**Issue by anqichen9856** [AY1920S1-CS2103T-T11-1/main#65]

**Comment by briyanii** [comment]
already working on this

**Comment by briyanii** [comment]
currently only 2 states (within allocated value and exceeded)
todo
- [ ] : different colours at various increments
- [ ] : gradient to match percentage
- [ ] : allow user to set some threshold? (budget feature, potential enchancement)

**Comment by briyanii** [comment]
additional incremental colours (4 at time of comment) implemented by @anqichen9856
