### ISSUE TITLE
Add feature to redo expense

### ISSUE THREAD

**Issue by czkay** [AY1920S1-CS2103T-T11-1/main#8]
[UNDO REDO]
As a careless person who is prone to typos, I can redo my previous command, so that I do not delete expenses by accident.

**Comment by briyanii** [comment]
after #6

**Comment by briyanii** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Feature: Undo last entered expense](https://trello.com/c/xnsPxJz5/18-feature-undo-last-entered-expense)
