### ISSUE TITLE
Add feature to search for past expenses

### ISSUE THREAD

**Issue by anqichen9856** [AY1920S1-CS2103T-T11-1/main#9]
As a foodie who frequently goes out with friends and pays for grab/restaurant bills, I can find a particular entry by typing a keyword, so that I can refer to a previous expense and know how much money my friend needs to pay me back. 

As a university student, I may often eat with friends. It is common for one person to settle the bill first and then we split it after. I want to be able to track expenses when I pay for the group and then let it calculate how much each person owes.

**Comment by briyanii** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add feature to search past expenses](https://trello.com/c/G4k16gbu/13-add-feature-to-search-past-expenses)

**Comment by briyanii** [comment]
existing feature (list / find)
